#ifndef __GLOBAL_CONSTANTS__
#define __GLOBAL_CONSTANTS__

#define MAX_LINE_LENGTH 80
#define MAX_PARAM_SIZE 20

/*Error types*/
#define ERR_ILLEGAL_COMMA -1
#define ERR_COMMAND_NOT_FOUND -2
#define ERR_MISSING_ARGUMENT -3
#define ERR_EXTRA_TEXT_NO_COMMA_AFTER_FIRST_PARAM -4
#define ERR_WORD_NOT_FOUND -5
#endif
